# Notebook for evaluating forecasts

In [ ]:
import pandas as pd
from sklearn.metrics import *

In [ ]:
# Replace with your csv file name
df_results = pd.read_csv("../Data/Submission/submission_A.csv")
# df_results = pd.read_csv("../Data/Submission/submission_B.csv")
df_solution = pd.read_csv("../Data/Solution_A.csv")

In [ ]:
df_results

          TIMESTAMP     POWER
0    20180201 01:00  0.877066
1    20180201 02:00  0.876072
2    20180201 03:00  0.824638
3    20180201 04:00  0.818938
4    20180201 05:00  0.823571
..              ...       ...
667  20180228 20:00  0.627626
668  20180228 21:00  0.650192
669  20180228 22:00  0.628153
670  20180228 23:00  0.614043
671  20180301 00:00  0.634865

[672 rows x 2 columns]

In [ ]:
df_solution

          TIMESTAMP     POWER
0    20180201 01:00  0.876351
1    20180201 02:00  0.921515
2    20180201 03:00  0.895380
3    20180201 04:00  0.898016
4    20180201 05:00  0.862974
..              ...       ...
667  20180228 20:00  0.666377
668  20180228 21:00  0.665494
669  20180228 22:00  0.740842
670  20180228 23:00  0.699803
671  20180301 00:00  0.710395

[672 rows x 2 columns]

In [ ]:
def evaluate_preds(df_own_predictions: pd.DataFrame, df_solution: pd.DataFrame):
    
    format = '%Y%m%d %H:%M'
    
    df_own_predictions['DATETIME'] = pd.to_datetime(df_own_predictions['TIMESTAMP'].astype("string"), format=format)
    df_solution['DATETIME'] = pd.to_datetime(df_solution['TIMESTAMP'].astype("string"), format=format)
    
    df_own_predictions = df_own_predictions.set_index(pd.DatetimeIndex(df_own_predictions['DATETIME']))
    df_solution = df_solution.set_index(pd.DatetimeIndex(df_solution['DATETIME']))
    
    df_own_predictions.sort_index()
    df_solution.sort_index()
    
    assert len(df_own_predictions) == len(df_solution)
    df_len = len(df_own_predictions)
    assert df_own_predictions['DATETIME'][0] == df_solution['DATETIME'][0]
    assert df_own_predictions['DATETIME'][df_len-1] == df_solution['DATETIME'][df_len-1]
    
    preds=[]
    actuals=[]
    for index, values in df_own_predictions.iterrows():
        preds.append(df_own_predictions.loc[[index]]['POWER'][0])
        actuals.append(df_solution.loc[[index]]['POWER'][0])
    score = r2_score(actuals, preds)
    
    print("R2 SCORE: %f" % (score))

In [ ]:
evaluate_preds(df_own_predictions=df_results, df_solution=df_solution)

C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  assert df_own_predictions['DATETIME'][0] == df_solution['DATETIME'][0]
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  assert df_own_predictions['DATETIME'][df_len-1] == df_solution['DATETIME'][df_len-1]
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])

R2 SCORE: 0.856987

C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  preds.append(df_own_predictions.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  actuals.append(df_solution.loc[[index]]['POWER'][0])
C:\Users\jostr\AppData\Local\Temp\ipykernel_96792\4118061343.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`